### PR TITLE
Copy readme contents to documentation project

### PR DESCRIPTION
**Pull request by Raithlin**
The creation of the Package Reference pages that replace the `readme.md` details.

### CODE REVIEW

**Review by warriordog — CHANGES_REQUESTED** [review]
@Raithlin Great work, thank you! I do have a couple of requests:
1. Could we move these to the "User Guide" section instead of "Dev Resources"? And maybe even add a sub-section to group them, like "Package Reference" or something.
2. Would you additionally *replace* the original files (in the code area) with just a header and a link to these new documentation files?

**Comment by Raithlin** [comment]
@warriordog I think I got this right, but without a local setup to mirror the github.io docs I can't be sure.

**Comment by warriordog** [comment]
@Raithlin sorry for not responding - I've been very busy recently. You can test locally by running `docfx docfx.json --serve` from the documentation folder. (side note - I should add that in the documentation somewhere.)

**Review by warriordog — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
